### ISSUE TITLE
Spanish book crash 1.12.2

### ISSUE THREAD

**Issue by losmochos** [Geforce132/SecurityCraft#120]
Hi
When turning the pages of the instruction book, on reaching the 6th page, the client gives the following error:

Description: Unexpected error

java.util.UnknownFormatConversionException: Conversion = ')'
    at java.util.Formatter.checkText(Formatter.java:2579)
    at java.util.Formatter.parse(Formatter.java:2565)
    at java.util.Formatter.format(Formatter.java:2501)
    at java.util.Formatter.format(Formatter.java:2455)
    at java.lang.String.format(String.java:2928)
    at net.geforcemods.securitycraft.util.ClientUtils.localize(ClientUtils.java:90)
    at net.geforcemods.securitycraft.gui.GuiSCManual.updateRecipeAndIcons(GuiSCManual.java:429)
    at net.geforcemods.securitycraft.gui.GuiSCManual.initGui(GuiSCManual.java:79)
    at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478)
    at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018)
    at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
    at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322)
    at net.geforcemods.securitycraft.items.ItemSCManual.onItemRightClick(ItemSCManual.java:21)
    at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClick(PlayerControllerMP.java:511)
    at net.optifine.override.PlayerControllerOF.processRightClick(PlayerControllerOF.java:80)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1597)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

full log:
https://paste.dimdev.org/quyezodogi.mccrash

Thanks for your work!

**Comment by bl4ckscor3** [comment]
Thanks for reporting, this has already been fixed in da35577136f776597396f2dc4ab3b951a7f626b3 for the next version. If you want to fix it yourself, close Minecraft, open the SecurityCraft jar file with WinRar/7zip, go to `assets/securitycraft/lang` and open `es_ES.lang` with a text editor, and at the end of line 360, replace `del 66%` with `de 2/3`.

**Comment by losmochos** [comment]
Thanks bl4ckscor3!
