### ISSUE TITLE
Keycard Crafting Crash

### ISSUE THREAD

**Issue by MLGTornadoGamer** [Geforce132/SecurityCraft#306]
I combined a limited use keycard with a normal keycard and it crashed. I am using [1.18.1]+SecurityCraft+v1.9.0.2-beta1 on a server. Only the client crashes.

<details>
<summary>Crash Report</summary>

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/2/22, 8:22 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font
at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:54) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:35) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:128) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:379) ~[forge-1.18.1-39.0.9-universal.jar%2373!:?] {re:classloading}
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:371) ~[forge-1.18.1-39.0.9-universal.jar%2373!:?] {re:classloading}
at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.optifine.reflect.Reflector.callVoid(Reflector.java:682) ~[OptiFine_1.18.1_HD_U_H4.jar%2374!:?] {re:classloading}
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1276) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:54) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:35) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:128) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei-1.18.1-9.1.2.50.jar%2362!:9.1.2.50] {re:classloading}
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:379) ~[forge-1.18.1-39.0.9-universal.jar%2373!:?] {re:classloading}
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:371) ~[forge-1.18.1-39.0.9-universal.jar%2373!:?] {re:classloading}
at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.optifine.reflect.Reflector.callVoid(Reflector.java:682) ~[OptiFine_1.18.1_HD_U_H4.jar%2374!:?] {re:classloading}
-- Screen render details --
Details:
Screen name: net.minecraft.client.gui.screens.inventory.CraftingScreen
Mouse location: Scaled: (237, 89). Absolute: (474.000000, 178.000000)
Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1276) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Affected level --
Details:
All players: 1 total; [LocalPlayer['TornadoGamer'/30549, l='ClientLevel', x=87.44, y=64.00, z=45.01]]
Chunk stats: 729, 464
Level dimension: minecraft:overworld
Level spawn location: World: (147,65,43), Section: (at 3,1,11 in 9,4,2; chunk contains blocks 144,-64,32 to 159,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Level time: 71820578 game time, 57100476 day time
Server brand: forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A}
at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:677) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2369!:?] {re:classloading,pl:runtimedistcleaner:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

</details>

**Comment by bl4ckscor3** [comment]
This is a JEI bug, update JEI.
