### ISSUE TITLE
Crash on camera 

### ISSUE THREAD

**Issue by checkium** [Geforce132/SecurityCraft#34]
I'm using the most recent securitycraft version for 1.7.10 with looking glass API also updated. When I try to use a camera, I crash.

**Comment by checkium** [comment]
```
java.lang.AbstractMethodError: net.geforcemods.securitycraft.imc.lookingglass.CameraAnimatorSecurityCamera.update(J)V
	at com.xcompwiz.lookingglass.entity.EntityCamera.tick(EntityCamera.java:92)
	at com.xcompwiz.lookingglass.client.proxyworld.WorldView.startRender(WorldView.java:120)
	at com.xcompwiz.lookingglass.render.WorldViewRenderManager.onRenderTick(WorldViewRenderManager.java:45)
	at com.xcompwiz.lookingglass.proxyworld.LookingGlassEventHandler.onRenderTick(LookingGlassEventHandler.java:102)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_10_LookingGlassEventHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.xcompwiz.lookingglass.entity.EntityCamera.tick(EntityCamera.java:92)
	at com.xcompwiz.lookingglass.client.proxyworld.WorldView.startRender(WorldView.java:120)
	at com.xcompwiz.lookingglass.render.WorldViewRenderManager.onRenderTick(WorldViewRenderManager.java:45)
	at com.xcompwiz.lookingglass.proxyworld.LookingGlassEventHandler.onRenderTick(LookingGlassEventHandler.java:102)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_10_LookingGlassEventHandler_onRenderTick_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['Checkium'/22741, l='MpServer', x=3781.45, y=72.62, z=929.49], EntityOtherPlayerMP['Mike_Smith_PT'/40932, l='MpServer', x=3770.88, y=73.94, z=937.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (3924,69,792), Chunk: (at 4,4,8 in 245,49; contains blocks 3920,0,784 to 3935,255,799), Region: (7,1; contains chunks 224,32 to 255,63, blocks 3584,0,512 to 4095,255,1023)
	Level time: 656861 game time, 89222 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 77 total; [EntityWitch['Bruxa'/41477, l='MpServer', x=3752.50, y=38.00, z=896.50], EntityClientPlayerMP['Checkium'/22741, l='MpServer', x=3786.71, y=74.62, z=923.92], EntityCreeper['Creeper'/41489, l='MpServer', x=3712.00, y=40.00, z=862.47], EntityCreeper['Creeper'/41490, l='MpServer', x=3720.50, y=39.00, z=861.50], EntityCreeper['Creeper'/41491, l='MpServer', x=3717.34, y=39.00, z=860.34], EntitySpider['Aranha'/40988, l='MpServer', x=3786.94, y=69.00, z=855.50], EntityClientPlayerMP['Checkium'/22741, l='MpServer', x=3781.45, y=72.62, z=929.49], EntityBat['Morcego'/41504, l='MpServer', x=3852.75, y=59.24, z=964.66], EntitySlime['Slime'/30240, l='MpServer', x=3828.31, y=11.24, z=879.69], EntityOtherPlayerMP['Mike_Smith_PT'/40932, l='MpServer', x=3783.25, y=72.06, z=931.31], EntitySkeleton['Esqueleto'/37154, l='MpServer', x=3761.16, y=44.67, z=922.50], EntityEnderman['Enderman'/42285, l='MpServer', x=3830.50, y=65.00, z=942.50], EntityBat['Morcego'/38707, l='MpServer', x=3806.53, y=47.10, z=936.50], EntityHorse['Cavalo'/51, l='MpServer', x=3794.13, y=69.00, z=857.16], EntitySpider['Aranha'/42547, l='MpServer', x=3738.50, y=74.00, z=995.50], EntityHorse['Cavalo'/54, l='MpServer', x=3806.88, y=68.00, z=887.22], EntityOtherPlayerMP['Mike_Smith_PT'/39248, l='MpServer', x=3784.47, y=71.00, z=930.78], EntitySpider['Aranha'/42555, l='MpServer', x=3746.50, y=74.00, z=995.50], EntityHorse['Cavalo'/68, l='MpServer', x=3820.94, y=67.00, z=878.75], EntityHorse['Cavalo'/69, l='MpServer', x=3820.22, y=67.00, z=876.53], EntityCreeper['Creeper'/42310, l='MpServer', x=3814.50, y=67.00, z=939.50], EntityCreeper['Creeper'/42566, l='MpServer', x=3785.00, y=70.00, z=984.44], EntitySkeleton['Esqueleto'/42314, l='MpServer', x=3810.63, y=67.00, z=934.91], EntityZombie['Zombie'/41291, l='MpServer', x=3775.78, y=69.00, z=918.22], EntityCreeper['Creeper'/38485, l='MpServer', x=3778.03, y=18.45, z=932.41], EntityZombie['Zombie'/38486, l='MpServer', x=3756.72, y=50.00, z=963.13], EntityCreeper['Creeper'/42329, l='MpServer', x=3816.50, y=66.00, z=946.50], EntityHorse['Cavalo'/90, l='MpServer', x=3827.00, y=67.00, z=860.94], EntityCreeper['Creeper'/42330, l='MpServer', x=3812.50, y=66.00, z=949.50], EntitySpider['Aranha'/42332, l='MpServer', x=3821.50, y=66.00, z=957.50], EntitySkeleton['Esqueleto'/40029, l='MpServer', x=3768.09, y=-56.64, z=921.50], EntityEnderman['Enderman'/42591, l='MpServer', x=3857.47, y=51.00, z=947.06], EntityZombie['Zombie'/42336, l='MpServer', x=3724.50, y=60.00, z=971.50], EntityZombie['Zombie'/42592, l='MpServer', x=3860.94, y=52.00, z=945.53], EntityPig['Porco'/109, l='MpServer', x=3845.03, y=66.00, z=911.97], EntityPig['Porco'/110, l='MpServer', x=3854.88, y=64.00, z=915.41], EntityOtherPlayerMP['Mike_Smith_PT'/28622, l='MpServer', x=3782.25, y=71.00, z=932.09], EntityBat['Morcego'/42608, l='MpServer', x=3806.91, y=54.65, z=971.69], EntityOtherPlayerMP['Mike_Smith_PT'/28622, l='MpServer', x=3725.56, y=35.00, z=857.09], EntitySheep['Ovelha'/123, l='MpServer', x=3855.84, y=64.00, z=867.16], EntityCreeper['Creeper'/41598, l='MpServer', x=3741.50, y=74.00, z=994.50], EntityBlitz['Blitz'/42370, l='MpServer', x=3818.50, y=66.00, z=938.50], EntityZombie['Zombie'/41604, l='MpServer', x=3747.50, y=74.00, z=982.50], EntityOtherPlayerMP['Mike_Smith_PT'/40932, l='MpServer', x=3770.88, y=73.94, z=937.50], EntityCreeper['Creeper'/42375, l='MpServer', x=3822.06, y=66.00, z=943.25], EntityZombie['Zombie'/42384, l='MpServer', x=3777.47, y=69.22, z=916.91], EntityCreeper['Creeper'/42389, l='MpServer', x=3704.50, y=-16.66, z=923.50], EntityWitch['Bruxa'/42401, l='MpServer', x=3824.50, y=67.00, z=858.50], EntityCreeper['Creeper'/41126, l='MpServer', x=3713.50, y=74.00, z=928.50], EntityOtherPlayerMP['Mike_Smith_PT'/334, l='MpServer', x=3769.50, y=73.00, z=936.50], EntityZombie['Zombie'/42410, l='MpServer', x=3823.50, y=67.00, z=855.50], EntityBat['Morcego'/21931, l='MpServer', x=3775.75, y=55.10, z=924.75], EntityChicken['Galinha'/40875, l='MpServer', x=3743.41, y=19.00, z=887.41], EntityZombie['Zombie'/28589, l='MpServer', x=3796.00, y=46.00, z=927.44], EntityHorse['Cavalo'/8110, l='MpServer', x=3781.59, y=71.00, z=866.22], EntityCreeper['Creeper'/42162, l='MpServer', x=3807.50, y=49.00, z=945.50], EntityCreeper['Creeper'/41395, l='MpServer', x=3834.50, y=65.00, z=939.50], EntitySkeleton['Esqueleto'/42429, l='MpServer', x=3768.50, y=72.00, z=969.50], EntityHorse['Cavalo'/18368, l='MpServer', x=3778.00, y=70.00, z=849.00], EntityChicken['Galinha'/18370, l='MpServer', x=3832.38, y=63.00, z=977.44], EntityZombie['Zombie'/42435, l='MpServer', x=3773.50, y=72.00, z=970.50], EntityOtherPlayerMP['Mike_Smith_PT'/40932, l='MpServer', x=3785.13, y=71.00, z=928.29], EntityChicken['Galinha'/18397, l='MpServer', x=3827.44, y=63.00, z=996.56], EntitySpider['Aranha'/42462, l='MpServer', x=3816.50, y=40.97, z=853.50], EntityZombie['Zombie'/42464, l='MpServer', x=3813.50, y=-27.70, z=850.50], EntityZombie['Zombie'/42465, l='MpServer', x=3820.50, y=-27.70, z=857.50], EntityZombie['Zombie'/42466, l='MpServer', x=3819.50, y=-27.70, z=854.50], EntityZombie['Zombie'/42467, l='MpServer', x=3819.50, y=-27.70, z=858.50], EntityOtherPlayerMP['Mike_Smith_PT'/40932, l='MpServer', x=3770.88, y=73.94, z=937.50], EntityCreeper['Creeper'/42469, l='MpServer', x=3753.72, y=71.00, z=855.50], EntitySkeleton['Esqueleto'/42470, l='MpServer', x=3748.50, y=72.00, z=856.50], EntityBat['Morcego'/41961, l='MpServer', x=3753.09, y=34.38, z=855.53], EntitySpider['Aranha'/42474, l='MpServer', x=3754.97, y=71.00, z=855.97], EntitySlime['Slime'/25837, l='MpServer', x=3802.54, y=35.00, z=925.31], EntityXPOrb['Esfera de Experiência'/41721, l='MpServer', x=3776.84, y=71.75, z=928.70], EntityXPOrb['Esfera de Experiência'/41722, l='MpServer', x=3776.91, y=71.75, z=928.76], EntityChicken['Galinha'/18431, l='MpServer', x=3856.16, y=62.47, z=932.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by bl4ckscor3** [comment]
Are you using LookingGlass 0.2.0.01 by chance? That version is not compatible with SecurityCraft, 0.2.0.00 works perfectly.

**Comment by checkium** [comment]
Yes, I was I tried downgrading it some minutes ago and it worked, the unique problem I found is that the cameras dont move (the camera (block) moves) but the screen stays always looking front

**Comment by bl4ckscor3** [comment]
That is interesting, probably some mod interference we can't control. So this issue is resolved, then?

**Comment by checkium** [comment]
Yes

**Comment by checkium** [comment]
![image](https://cloud.githubusercontent.com/assets/9268058/19021937/9d19244a-88c4-11e6-9764-6f6a4cb99269.png)
I'm using this mods

**Comment by checkium** [comment]
Wait, anyway I rejoined the server and the camera is now moving

**Comment by checkium** [comment]
Another problem, there's no crafting for the code thing.

**Comment by bl4ckscor3** [comment]
If the codebreaker can't be crafted, the server disabled it.

**Comment by checkium** [comment]
@bl4ckscor3 Not the code breaker, is the thing you input code and then it opens things near it, I don't know the name in english

**Comment by bl4ckscor3** [comment]
The Keypad. Place down a frame and rightclick it with a Key Panel.
