### ISSUE TITLE
[Bug + Crash] Crashing when placing a module on an inventory scanner that is not connected.

### ISSUE THREAD

**Issue by Vhexp** [Geforce132/SecurityCraft#405]
Experiencing crashes when attempting to place a module on an inventory scanner that is not connected to another scanner.
### **[CRASH LOG]**

`java.lang.NullPointerException: Container click
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at net.geforcemods.securitycraft.blockentities.InventoryScannerBlockEntity.onModuleInserted(InventoryScannerBlockEntity.java:306) ~[%5B1.19.2%5D+SecurityCraft+v1.9.4.jar%23146!/:1.9.4] {re:classloading}
	at net.geforcemods.securitycraft.api.IModuleInventory.setStackInSlot(IModuleInventory.java:241) ~[%5B1.19.2%5D+SecurityCraft+v1.9.4.jar%23146!/:1.9.4] {re:classloading}
	at net.minecraftforge.items.SlotItemHandler.m_5852_(SlotItemHandler.java:47) ~[forge-1.19.2-43.2.4-universal.jar%23152!/:?] {re:classloading}
	at net.geforcemods.securitycraft.inventory.CustomizeBlockMenu$CustomSlotItemHandler.m_5852_(CustomizeBlockMenu.java:143) ~[%5B1.19.2%5D+SecurityCraft+v1.9.4.jar%23146!/:1.9.4] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:166) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:409) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:293) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_171799_(MultiPlayerGameMode.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6597_(AbstractContainerScreen.java:554) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6348_(AbstractContainerScreen.java:519) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
`

**Comment by bl4ckscor3** [comment]
We no longer update the mod for 1.19.2 and this bug [has been fixed in v1.9.5](https://github.com/Geforce132/SecurityCraft/blob/1.19.3/Changelog.md?plain=1#L61) of the mod.
