### ISSUE TITLE
Game gets stuck after exiting camera monitor 

### ISSUE THREAD

**Issue by Gamer101233** [Geforce132/SecurityCraft#457]
### Issue description

Every time i go to use the camera monitor in game it will work normal for a few times then out of no where when i go to use it again and then exit the monitor i get stuck and cant move or right click the monitor if i do right click the monitor it will close right as i click it and the only way to get unstuck is to leave the world and rejoin then it happenes again after a few more uses of the camera monitor.
There is no crash log it seems as it does not fully crash the game.

### Steps to reproduce

not sure what to do because it happens on its own but, all i knnow is you keep using the camera monitor and after a few times when you exit your player gets stuck and unable to do anything.

### Minecraft version

1.12.2

### Forge version

14.23.5.2859

### SecurityCraft version

v1.9.7

**Comment by bl4ckscor3** [comment]
Do you perhaps have a latest.log or debug.log of a time when this happened? I can't reproduce this; Perhaps the log will give some more insight. It might also be a mod incompatibility of some sort, but we have little to go on in any case.

**Comment by Gamer101233** [comment]
i took a look in all the logs at the time of the issue there is nothing with a error with security craft during the time of the issue im not sure where i can find the debug log.

**Comment by bl4ckscor3** [comment]
The debug.log file is in the same place as the latest.log file.

**Comment by Gamer101233** [comment]
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.play.server.SPacketEntity.func_149065_a(SourceFile:161) ~[jj.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147259_a(NetHandlerPlayClient.java:620) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketEntity.func_148833_a(SourceFile:152) ~[jj.class:?]
	at net.minecraft.network.play.server.SPacketEntity$S15PacketEntityRelMove.func_148833_a(SourceFile:67) ~[jj$a.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]


thats a error that may be relavent but, was spammed a lot.

**Comment by bl4ckscor3** [comment]
Please post the full log of when the camera monitor issue happened, not just a snippet.

**Comment by Gamer101233** [comment]
https://pastebin.com/660gPhdn

**Comment by Gamer101233** [comment]
any update on this issue is it fixed?
if so do i need to download a newer version of the mod?

**Comment by bl4ckscor3** [comment]
We haven't been able to track this issue down to be able to fix it.

**Comment by bl4ckscor3** [comment]
Fixed in v1.9.10.1.
