### ISSUE TITLE
The server crashed after entering the wrong briefcase password multiple times

### ISSUE THREAD

**Issue by XiaoYAqwq** [Geforce132/SecurityCraft#550]
### Issue description

Game version:1.16.5 with SecurityCraft v1.9.12
My server members entered the wrong briefcase password multiple times in an accident, and then the server crashed. The crash report is as follows:
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.util.text.ITextComponent net.minecraft.item.Item.func_200296_o()'
	at net.geforcemods.securitycraft.network.server.CheckBriefcasePasscode.handle(CheckBriefcasePasscode.java:47) ~[securitycraft:v1.9.12] {re:classloading}
	at net.geforcemods.securitycraft.RegistrationHandler.lambda$null$0(RegistrationHandler.java:238) ~[securitycraft:v1.9.12] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:203) ~[forge:?] {re:classloading}
	at net.geforcemods.securitycraft.RegistrationHandler.lambda$registerPacket$1(RegistrationHandler.java:238) ~[securitycraft:v1.9.12] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[mohist-1.16.5-1241-universal.jar:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[mohist-1.16.5-1241-universal.jar:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:148) ~[mohist-1.16.5-1241-universal.jar:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:66) ~[mohist-1.16.5-1241-universal.jar:?] {re:classloading,re:mixin}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:248) ~[mohist-1.16.5-1241-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:240) ~[mohist-1.16.5-1241-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[mohist-1.16.5-1241-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284) ~[mohist-1.16.5-1241-server.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:80) ~[forge:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:80) ~[forge:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2646) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:tac.mixins.json:common.ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:971) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:954) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:948) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:934) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimapfair:xaero_minecraftserver,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {}

### Steps to reproduce

1.start 1.16.5 server (Mohist) with SC,
2.Take out the briefcase and enter the wrong password multiple times,
3.server crashed

### Minecraft version

1.16.5

### Forge/NeoForge version

36.2.43

### SecurityCraft version

v1.9.12

**Comment by bl4ckscor3** [comment]
Thanks for reporting! Until we release the version with the fix for this (will be a while), you can work around this issue by disabling the `passcode_spam_log_warning_enabled` server config setting.

**Comment by XiaoYAqwq** [comment]
> Thanks for reporting! Until we release the version with the fix for this (will be a while), you can work around this issue by disabling the `passcode_spam_log_warning_enabled` server config setting.

Thank you for your reply! I will try to modify the config and wish the mod continued improvement!
